### ISSUE TITLE
Singlequote enclosed pattern inside of typedef (yangson.exceptions.InvalidArgument)

### ISSUE THREAD

**Issue by JHolcman-T** [CZ-NIC/yangson#100]
There is an Issue/Bug with patterns. When an pattern argument is enclosed with singlequotes and conatins "\\\\" yangson produces following exception:

```
Traceback (most recent call last):
  File "/home/hjm02/PycharmProjects/yang_diff_wab/json_builder/__main__.py", line 58, in <module>
    dm = DataModel.from_file(b.json_file.name, tuple(paths))
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/datamodel.py", line 58, in from_file
    return cls(yltxt, mod_path, description)
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/datamodel.py", line 85, in __init__
    self._build_schema()
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/datamodel.py", line 195, in _build_schema
    self.schema._handle_substatements(
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/schemanode.py", line 246, in _handle_substatements
    method(s, sctx)
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/schemanode.py", line 726, in _leaf_stmt
    node.type = DataType._resolve_type(
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/datatype.py", line 185, in _resolve_type
    res = cls._derived_type(stmt, sctx, loc if s else typ)
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/datatype.py", line 205, in _derived_type
    res._handle_properties(ts, sc)
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/datatype.py", line 222, in _handle_properties
    self._handle_restrictions(stmt, sctx)
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/datatype.py", line 449, in _handle_restrictions
    self.patterns.append(Pattern(
  File "/home/hjm02/PycharmProjects/yang_diff_wab/virtual_environment_p_3.9.0/lib/python3.9/site-packages/yangson/constraint.py", line 142, in __init__
    raise InvalidArgument(pattern) from None
yangson.exceptions.InvalidArgument: [a-zA-Z0-9!#$%&=:/_\\\\|\\.\\-\\^\\?\\*\\+\\{\\}\\(\\)\\[\\]]+
```

Rule from RFC7950 at page 67
https://tools.ietf.org/html/rfc7950#section-7.4.1
```
                          The type's Substatements
               +------------------+---------+-------------+
               | substatement     | section | cardinality |
               +------------------+---------+-------------+
               | base             | 7.18.2  | 0..n        |
               | bit              | 9.7.4   | 0..n        |
               | enum             | 9.6.4   | 0..n        |
               | fraction-digits  | 9.3.4   | 0..1        |
               | length           | 9.4.4   | 0..1        |
               | path             | 9.9.2   | 0..1        |
               | pattern          | 9.4.5   | 0..n        |
               | range            | 9.2.4   | 0..1        |
               | require-instance | 9.9.3   | 0..1        |
               | type             | 7.4     | 0..n        |
               +------------------+---------+-------------+
```

YANG module
```YANG
module test3 {

  yang-version "1.1";
  namespace "test3.com";
  prefix test3;

  typedef nodename {
    type string {
      pattern '[a-zA-Z0-9!#$%&=:/_\\\\|\\.\\-\\^\\?\\*\\+\\{\\}\\(\\)\\[\\]]+';  # This doesn't work
    }
  }

  leaf pattern-test1 {
    type nodename;
  }

  leaf pattern-test2 {
    type string {
     pattern '[a-zA-Z0-9!#$%&=:/_\\\\|\\.\\-\\^\\?\\*\\+\\{\\}\\(\\)\\[\\]]+';  # This doesn't work as well
    }
  }
}
```

**Comment by llhotka** [comment]
The regex pattern is invalid as it contains an unescaped left brace character (`[`) inside the `[...]` character class:
```
[a-zA-Z0-9!#$%&=:/_\\\\|\\.\\-\\^\\?\\*\\+\\{\\}\\(\\)\\[\\]]+
                                                        ^
```
Are you aware that YANG performs **no backslash escapes** inside single-quoted strings? See [sec. 6.1.3](https://www.rfc-editor.org/rfc/rfc7950.html#section-6.1.3) in RFC 7950.

**Comment by JHolcman-T** [comment]
> The regex pattern is invalid as it contains an unescaped left brace character (`[`) inside the `[...]` character class:
> 
> ```
> [a-zA-Z0-9!#$%&=:/_\\\\|\\.\\-\\^\\?\\*\\+\\{\\}\\(\\)\\[\\]]+
>                                                         ^
> ```
> 
> Are you aware that YANG performs **no backslash escapes** inside single-quoted strings? See [sec. 6.1.3](https://www.rfc-editor.org/rfc/rfc7950.html#section-6.1.3) in RFC 7950.

That is very werid but fine. I found this pattern in yang file that is directly from cisco, so I thoght it would work... (This pattern works with cisco specific software without any problems.) Would it be possible to implement an option to disable pattern syntax-check? When not just close this issue.

**Comment by llhotka** [comment]
Are you sure that the original Cisco module uses single quotes? It would be a different story with double quotes.

If so, I'd suggest to complain to Cisco. It seems that the expression could be fixed simply by replacing every backslash pair by a single backslash.
