### ISSUE TITLE
No attribute '_handle_substatements' when loading ietf-arp

### ISSUE THREAD

**Issue by raddessi** [CZ-NIC/yangson#21]
Hi, I'm trying to load the ietf-arp model which needs ietf-ip model but get an error when doing so.

- ietf-arp: https://raw.githubusercontent.com/YangModels/yang/master/experimental/ietf-extracted-YANG-modules/ietf-arp@2019-02-21.yang
- ietf-ip: https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-ip%402018-02-22.yang

My library config:
```json
{
  "ietf-yang-library:modules-state": {
    "module-set-id": "ae595da11ace92c0d881995fa7e56bbe86f1f48e9",
    "module": [
      {
        "name": "ietf-arp",
        "revision": "2019-02-21",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-arp",
        "conformance-type": "implement",
        "schema": "https://raw.githubusercontent.com/YangModels/yang/master/experimental/ietf-extracted-YANG-modules/ietf-arp@2019-02-21.yang"
      },
      {
        "name": "ietf-ip",
        "revision": "2018-02-22",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-ip",
        "conformance-type": "import",
        "schema": "https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-ip%402018-02-22.yang"
      },


      {
        "name": "ietf-inet-types",
        "revision": "2013-07-15",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-inet-types",
        "conformance-type": "import",
        "schema": "https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-inet-types.yang"
      },
      {
        "name": "ietf-yang-types",
        "revision": "2013-07-15",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-yang-types",
        "conformance-type": "import",
        "schema": "https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-yang-types.yang"
      },
      {
        "name": "iana-if-type",
        "revision": "2017-01-19",
        "namespace": "urn:ietf:params:xml:ns:yang:iana-if-type",
        "conformance-type": "implement",
        "schema": "https://github.com/YangModels/yang/blob/master/experimental/odp/iana-if-type.yang"
      },
      {
        "name": "openconfig-yang-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-yang-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/types/openconfig-yang-types.yang"
      },
      {
        "name": "openconfig-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/types/openconfig-types.yang"
      },
      {
        "name": "openconfig-interfaces",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-interfaces",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-interfaces.yang"
      },
      {
        "name": "openconfig-extensions",
        "revision": "2018-10-17",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-extensions",
        "conformance-type": "import",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/openconfig-extensions.yang"
      },
      {
        "name": "ietf-interfaces",
        "revision": "2014-05-08",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-interfaces",
        "conformance-type": "import",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-interfaces.yang"
      },
      {
        "name": "openconfig-vlan",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-vlan",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/vlan/openconfig-vlan.yang"
      },
      {
        "name": "openconfig-vlan-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-vlan-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/vlan/openconfig-vlan-types.yang"
      },
      {
        "name": "openconfig-lldp",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-lldp",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/lldp/openconfig-lldp.yang"
      },
      {
        "name": "openconfig-lldp-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-lldp-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/lldp/openconfig-lldp-types.yang"
      }
    ]
  }
}

```

What I get when running:
```bash
$ yangson ./yang/yang-library-data.json --path ./yang/yang-modules/ietf:./yang/yang-modules/openconfig
Traceback (most recent call last):
  File "/usr/local/bin/yangson", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/yangson/__main__.py", line 112, in main
    dm = DataModel(yl, tuple(sp.split(":")))
  File "/usr/local/lib/python3.7/site-packages/yangson/datamodel.py", line 85, in __init__
    self._build_schema()
  File "/usr/local/lib/python3.7/site-packages/yangson/datamodel.py", line 190, in _build_schema
    self.schema._augment_stmt(aug, sctx)
  File "/usr/local/lib/python3.7/site-packages/yangson/schemanode.py", line 570, in _augment_stmt
    target._handle_substatements(stmt, sctx)
AttributeError: 'NoneType' object has no attribute '_handle_substatements'
```

I'm running v1.3.39
```bash
$ yangson --version
yangson 1.3.39
```

I did see a similar failure in https://github.com/CZ-NIC/yangson/issues/15 but that should be resolved in my current version unless I'm missing something. I'm not even sure they are related, I'm still trying to get familiar with yang modeling.

**Comment by llhotka** [comment]
The problem was in your YANG library data. First, it didn't include some of the openconfig modules that are imported elsewhere, such as `openconfig-if-ethernet`. After I added these, I was able to reproduce your error. It is caused by the fact that the conformance type (as specified in the YANG library) for modules `ietf-interfaces` and `ietf-ip` is `import` but it should be `implement`! With your YANG Library the nodes from those two modules aren't present in the schema, but one module tries to augment them, which of course fails. Below is the corrected YANG library that works for me:
```
{
  "ietf-yang-library:modules-state": {
    "module-set-id": "ae595da11ace92c0d881995fa7e56bbe86f1f48e9",
    "module": [
      {
        "name": "ietf-arp",
        "revision": "2019-02-21",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-arp",
        "conformance-type": "implement",
        "schema": "https://raw.githubusercontent.com/YangModels/yang/master/experimental/ietf-extracted-YANG-modules/ietf-arp@2019-02-21.yang"
      },
      {
        "name": "ietf-ip",
        "revision": "2018-02-22",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-ip",
        "conformance-type": "implement",
        "schema": "https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-ip%402018-02-22.yang"
      },
      {
        "name": "ietf-inet-types",
        "revision": "2013-07-15",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-inet-types",
        "conformance-type": "import",
        "schema": "https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-inet-types.yang"
      },
      {
        "name": "ietf-yang-types",
        "revision": "2013-07-15",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-yang-types",
        "conformance-type": "import",
        "schema": "https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-yang-types.yang"
      },
      {
        "name": "iana-if-type",
        "revision": "2017-01-19",
        "namespace": "urn:ietf:params:xml:ns:yang:iana-if-type",
        "conformance-type": "implement",
        "schema": "https://github.com/YangModels/yang/blob/master/experimental/odp/iana-if-type.yang"
      },
      {
        "name": "openconfig-yang-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-yang-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/types/openconfig-yang-types.yang"
      },
      {
        "name": "openconfig-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/types/openconfig-types.yang"
      },
      {
        "name": "openconfig-interfaces",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-interfaces",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-interfaces.yang"
      },
      {
        "name": "openconfig-if-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-if-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-types.yang"
      },
      {
        "name": "openconfig-if-ethernet",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-if-ethernet",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-ethernet.yang"
      },
      {
        "name": "openconfig-if-aggregate",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-if-aggregate",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-aggregate.yang"
      },
      {
        "name": "openconfig-extensions",
        "revision": "2018-10-17",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-extensions",
        "conformance-type": "import",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/openconfig-extensions.yang"
      },
      {
        "name": "ietf-interfaces",
        "revision": "2014-05-08",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-interfaces",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-interfaces.yang"
      },
      {
        "name": "openconfig-vlan",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-vlan",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/vlan/openconfig-vlan.yang"
      },
      {
        "name": "openconfig-vlan-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-vlan-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/vlan/openconfig-vlan-types.yang"
      },
      {
        "name": "openconfig-lldp",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-lldp",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/lldp/openconfig-lldp.yang"
      },
      {
        "name": "openconfig-lldp-types",
        "revision": "2018-11-21",
        "namespace": "urn:ietf:params:xml:ns:yang:openconfig-lldp-types",
        "conformance-type": "implement",
        "schema": "https://github.com/openconfig/public/blob/master/release/models/lldp/openconfig-lldp-types.yang"
      }
    ]
  }
}
```

**Comment by raddessi** [comment]
Ahh.. that makes sense. I had hit some other error which was why I thought the 2nd should have been set to import. Thank you very much for your response :)

**Comment by llhotka** [comment]
A more intelligible error message is needed.
