### ISSUE TITLE
yangson.exceptions.InvalidArgument exception with mkylib.py tool

### ISSUE THREAD

**Issue by javcasalc** [CZ-NIC/yangson#40]
Hi

I'm trying to build json library yang file using mkylib tool, but it I'm unable to get it work. I'm sure I'm doing something wrong:
```
$ python yangson/tools/python/mkylib.py yang-models/standard/ietf/RFC                                                                      
Traceback (most recent call last):
  File "yangson/tools/python/mkylib.py", line 112, in <module>
    sys.exit(main())
  File "yangson/tools/python/mkylib.py", line 71, in main
    module_entry(yf)
  File "yangson/tools/python/mkylib.py", line 35, in module_entry
    mst = mp.statement()
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 286, in statement
    res.substatements = self.substatements()
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 390, in substatements
    res.append(self.statement())
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 286, in statement
    res.substatements = self.substatements()
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 390, in substatements
    res.append(self.statement())
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 286, in statement
    res.substatements = self.substatements()
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 390, in substatements
    res.append(self.statement())
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 281, in statement
    sub = self.argument()
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 302, in argument
    self.dq_argument()
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 353, in dq_argument
    if self._escape else self.input[start:self.offset])
  File "/home/ubuntu/miniconda3/envs/python37/lib/python3.7/site-packages/yangson/statement.py", line 194, in unescape
    raise InvalidArgument(text) from None
yangson.exceptions.InvalidArgument: \S+
```

I'm trying to parse directory https://github.com/YangModels/yang/tree/master/standard/ietf/RFC

Thanks,
J.

**Comment by llhotka** [comment]
It is a bug (probably) in the `ietf-ipfix-psamp@2012-09-05.yang` module: The double-quoted argument `"\S+"` contains an illegal escape. See [sec. 6.1.3](https://www.rfc-editor.org/rfc/rfc7950.html#section-6.1.3) in RFC 7950.

An easy fix is to change double quotes into single quotes.
