### ISSUE TITLE
Cannot augment node behind disabled feature

### ISSUE THREAD

**Issue by iwanb** [CZ-NIC/yangson#62]
E.g. given this library:
```
{
  "ietf-yang-library:modules-state": {
    "module-set-id": "",
    "module": [
      {
        "name": "ietf-netconf",
        "revision": "2011-06-01",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-netconf",
        "conformance-type": "implement"
      },
      {
        "name": "ietf-netconf-with-defaults",
        "revision": "2011-06-01",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults",
        "conformance-type": "implement"
      },
      {
        "name": "ietf-yang-types",
        "revision": "2013-07-15",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-yang-types",
        "conformance-type": "import"
      },
      {
        "name": "ietf-inet-types",
        "revision": "2013-07-15",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-inet-types",
        "conformance-type": "import"
      },
      {
        "name": "ietf-datastores",
        "revision": "2018-02-14",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-datastores",
        "conformance-type": "import"
      },
      {
        "name": "ietf-origin",
        "revision": "2018-02-14",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-origin",
        "conformance-type": "implement"
      },
      {
        "name": "ietf-yang-metadata",
        "revision": "2016-08-05",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-yang-metadata",
        "conformance-type": "import"
      },
      {
        "name": "ietf-netconf-nmda",
        "revision": "2019-01-07",
        "namespace": "urn:ietf:params:xml:ns:yang:ietf-netconf-nmda",
        "conformance-type": "implement"
      }
    ]
  }
}
```

Where ietf-netconf-nmda augments a node in ietf-netconf behind a feature, yangson says the augment target is missing:
```
$ yangson -p yang/standard/ietf/RFC/ yang-library.json
Traceback (most recent call last):
  File "/home/ibriquem/ws/external/yangson/.venv/bin/yangson", line 11, in <module>
    load_entry_point('yangson', 'console_scripts', 'yangson')()
  File "/home/ibriquem/ws/external/yangson/yangson/__main__.py", line 112, in main
    dm = DataModel(yl, tuple(sp.split(":")))
  File "/home/ibriquem/ws/external/yangson/yangson/datamodel.py", line 85, in __init__
    self._build_schema()
  File "/home/ibriquem/ws/external/yangson/yangson/datamodel.py", line 190, in _build_schema
    self.schema._augment_stmt(aug, sctx)
  File "/home/ibriquem/ws/external/yangson/yangson/schemanode.py", line 578, in _augment_stmt
    raise MissingAugmentTarget(stmt.argument)
yangson.exceptions.MissingAugmentTarget: /nc:validate/nc:input/nc:source/nc:config-source
```

It says the augment target is missing, but AFAIK the augment should be applied on the schema tree without taking features into account. I think that tree is not built in yangson, so an alternative is to check at each level of the path if the node is hidden behind a feature instead of being missing, and ignore the augment in that case.

**Comment by llhotka** [comment]
Fixed in version 1.4.3. A missing augment target (due to unsupported feature or another reason) is now silently ignored.
