### ISSUE TITLE
It seems that yangson incorrectly parses "pattern" parameter.

### ISSUE THREAD

**Issue by artgromov** [CZ-NIC/yangson#7]
I was trying to start jetconf server and got the following error while populating yang modules dir:
```
(jetconf_test) [admin@agromov jetconf_test]$ ~/anaconda3/envs/jetconf_test/bin/jetconf -c config.yml
2018-04-03 19:11:53,901 INFO     Jetconf version 0.3.4
2018-04-03 19:11:53,903 INFO     Using config:
GLOBAL:
  BACKEND_PACKAGE: jetconf_jukebox
  DATA_JSON_FILE: /home/admin/Dropbox/Dev/Python/jetconf_test/data.json.jb
  LOGFILE: '-'
  LOG_DBG_MODULES:
  - usr_conf_data_handlers
  - knot_api
  - nacm
  - data
  LOG_LEVEL: debug
  PERSISTENT_CHANGES: false
  PIDFILE: /home/admin/Dropbox/Dev/Python/jetconf_test/jetconf.pid
  TIMEZONE: Europe/Moscow
  VALIDATE_TRANSACTIONS: true
  YANG_LIB_DIR: /home/admin/Dropbox/Dev/Python/jetconf_test/yang
HTTP_SERVER:
  API_ROOT: /restconf
  API_ROOT_RUNNING: /restconf_running
  CA_CERT: /home/admin/Dropbox/Dev/Python/jetconf_test/ca.pem
  DBG_DISABLE_CERTS: false
  DOC_DEFAULT_NAME: index.html
  DOC_ROOT: /home/admin/Dropbox/Dev/Python/jetconf_test/www
  LISTEN_LOCALHOST_ONLY: false
  PORT: 8443
  SERVER_NAME: jetconf-h2
  SERVER_SSL_CERT: /home/admin/Dropbox/Dev/Python/jetconf_test/server.crt
  SERVER_SSL_PRIVKEY: /home/admin/Dropbox/Dev/Python/jetconf_test/server.key
  UPLOAD_SIZE_LIMIT: 1
NACM:
  ALLOWED_USERS:
  - lojza@mail.cz
  ENABLED: true

Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/jetconf_test/bin/jetconf", line 11, in <module>
    sys.exit(main())
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/jetconf/__main__.py", line 144, in main
    jc.init()
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/jetconf/jetconf.py", line 62, in init
    datamodel = DataModel(yang_lib_str, [yang_mod_dir])
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/datamodel.py", line 84, in __init__
    self.schema_data = SchemaData(self.yang_library, mod_path)
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/schemadata.py", line 94, in __init__
    self._from_yang_library(yang_lib)
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/schemadata.py", line 122, in _from_yang_library
    mod = self._load_module(name, rev)
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/schemadata.py", line 154, in _load_module
    res = ModuleParser(infile.read()).parse()
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 144, in parse
    res = self.statement()
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 262, in statement
    res.substatements = self.substatements()
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 366, in substatements
    res.append(self.statement())
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 262, in statement
    res.substatements = self.substatements()
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 366, in substatements
    res.append(self.statement())
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 262, in statement
    res.substatements = self.substatements()
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 366, in substatements
    res.append(self.statement())
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 257, in statement
    sub = self.argument()
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 278, in argument
    self.dq_argument()
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 329, in dq_argument
    if self._escape else self.input[start:self.offset])
  File "/home/admin/anaconda3/envs/jetconf_test/lib/python3.6/site-packages/yangson/statement.py", line 171, in unescape
    raise InvalidArgument(text) from None
yangson.exceptions.InvalidArgument: \*
```

I use yang data models from here: https://github.com/YangModels/yang

The only difference to make it work is replacing " with ' :
```
(jetconf_test) [admin@agromov jetconf_test]$ diff yang_models_repo/standard/ietf/RFC/ietf-netconf-acm@2012-02-22.yang yang/ietf-netconf-acm@2012-02-22.yang 
103c103
<       pattern "\*";
---
>       pattern '\*';
144c144
<       pattern "[^\*].*";
---
>       pattern '[^\*].*';
```

I think that standard yang modules should be used without any modifications.

**Comment by llhotka** [comment]
This is a known problem, see [errata](https://www.rfc-editor.org/errata/eid3863). Please use the NACM module from [RFC 8341](https://tools.ietf.org/html/rfc8341).
